language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t trav_env_var --build-arg DOCKER_USERNAME=${DOCKER_USERNAME} .
  - docker tag simple-node iniakponode/trav_env_var:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push iniakponode/trav_env_var
